In [26]:
from transformers import AutoModelForSeq2SeqLM
from datasets import load_from_disk
from pprint import pprint
import numpy as np
import sys
import os

In [3]:
print(set(os.listdir("./lang_splits/")) - set(os.listdir("./lang_models/")))

set()


In [34]:
batch_idxs = np.array_split(np.array(list(range(86))), 4)

for b1_idxs in batch_idxs:
    for b2_idxs in batch_idxs:
        print(b1_idxs, b2_idxs)

#print(np.meshgrid([1, 2, 3, 8], [3, 2, 9, 1]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43] [22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43] [44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40

In [36]:
pretrained_mt5 = AutoModelForSeq2SeqLM.from_pretrained("google/mt5-small")

In [37]:
pprint(pretrained_mt5.state_dict()["shared.weight"].size()[0])

pprint(list(pretrained_mt5.state_dict().keys()))
# decoder.block.7.layer.2.DenseReluDense.wi_0.weight
# decoder.block.7.layer.2.DenseReluDense.wi_1.weight
# decoder.block.7.layer.2.DenseReluDense.wo.weight
# encoder.block.7.layer.1.DenseReluDense.wi_0.weight
# encoder.block.7.layer.1.DenseReluDense.wi_1.weight
# encoder.block.7.layer.1.DenseReluDense.wo.weight
# decoder.block.7.layer.1.EncDecAttention.q.weight
# decoder.block.7.layer.1.EncDecAttention.k.weight
# decoder.block.7.layer.1.EncDecAttention.v.weight
# decoder.block.7.layer.1.EncDecAttention.o.weight
# encoder.block.7.layer.0.SelfAttention.q.weight
# encoder.block.7.layer.0.SelfAttention.k.weight
# encoder.block.7.layer.0.SelfAttention.v.weight
# encoder.block.7.layer.0.SelfAttention.o.weight
# shared.weight


250112
['shared.weight',
 'encoder.embed_tokens.weight',
 'encoder.block.0.layer.0.SelfAttention.q.weight',
 'encoder.block.0.layer.0.SelfAttention.k.weight',
 'encoder.block.0.layer.0.SelfAttention.v.weight',
 'encoder.block.0.layer.0.SelfAttention.o.weight',
 'encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight',
 'encoder.block.0.layer.0.layer_norm.weight',
 'encoder.block.0.layer.1.DenseReluDense.wi_0.weight',
 'encoder.block.0.layer.1.DenseReluDense.wi_1.weight',
 'encoder.block.0.layer.1.DenseReluDense.wo.weight',
 'encoder.block.0.layer.1.layer_norm.weight',
 'encoder.block.1.layer.0.SelfAttention.q.weight',
 'encoder.block.1.layer.0.SelfAttention.k.weight',
 'encoder.block.1.layer.0.SelfAttention.v.weight',
 'encoder.block.1.layer.0.SelfAttention.o.weight',
 'encoder.block.1.layer.0.layer_norm.weight',
 'encoder.block.1.layer.1.DenseReluDense.wi_0.weight',
 'encoder.block.1.layer.1.DenseReluDense.wi_1.weight',
 'encoder.block.1.layer.1.DenseReluDense.wo.weight'

In [2]:
data = load_from_disk("./lang_splits/yi")

In [4]:
print(data["train"]["text"][0])

דעם מולטיפונקטיאָנאַל געפירט אַרבעט ליכט איז מאָונטעד דורך מאַגנעט מיט וסב רעזולטאַט פֿאַר נויטפאַל מאַכט באַנק. די מאַגנאַץ זענען געבויט אין 2 ענדס פון ליכט צו צוטשעפּען רובֿ פון סערפאַסיז. עס האט אַ דוראַבאַל קאַנסטראַקטאַד אַלומינום גוף און די געפירט ליכט טראגט 450 לומאַנז, פּאַוערד דורך 5200 מאַה קריקאָנלאָדלעך באַטאַרייע (לענג: 223 מם). פּראַוויידינג בוילעט ילומאַניישאַן, עס אויך פֿעיִקייטן 3-דימאַבלע ברייטנאַס לעוועלס צוזאמען מיט סטראָבע און סאָס פאַנגקשאַנז. עס אויך גיט אַ מאָדע פון ​​קאָמאַר אָפּטרייַביק לאָמפּ ווען געוויינט פֿאַר באַקיאַרד, קעמפּינג. עס איז ידעאַל פֿאַר מאַשין ריפּערז, קעמפּינג, באָוטינג אָדער ביי אַ קוקאָוט. און אויך פֿאַר וואַרשטאַט, גאַראַזש, קעלער, קיך אָדער אַרום די הויז און באַקיאַרד
אָנפרעגדעטאַל
רוף אונז
צימער 606, 1סט בילדינג פון באַיטאָנג, ווייכווארג פּאַרק ווו, דזשימעי, קסיאַמען, טשיינאַ
טעלעפאָן: 0086-13666087358
טעלעפאָן: 0086-15985812061
בליצפּאָסט: ywh@loveliking.com
אָנפרעג פֿאַר פּרייסליסט
פֿאַר ינקוועריז וועגן אונדזער פּראָדוקטן אָדער פּרייסל